apiVersion: core.jenkins-x.io/v4beta1
kind: Requirements
spec:
  autoUpdate:
    enabled: false
    schedule: ""
  cluster:
    chartRepository: http://bucketrepo.jx.svc.cluster.local/bucketrepo/charts/
    clusterName: kind
    devEnvApprovers:
    - todo
    environmentGitOwner: todo
    gitKind: github
    gitName: github
    gitServer: https://github.com
    provider: minikube
    registry: 10.108.180.139
  environments:
  - key: dev
    owner: cybaspace
    repository: jx3
  - key: staging
  - key: production
  ingress:
    domain: 192.168.64.37.nip.io
    externalDNS: false
    kind: ingress
    namespaceSubDomain: -jx.
    tls:
      email: ""
      enabled: false
      production: false
  pipelineUser:
    username: cybaspace
  repository: bucketrepo
  secretStorage: local
  vault: {}
  webhook: lighthouse
